### ISSUE TITLE
Ola, problema com o packge de musica

### ISSUE THREAD

**Issue by SulistinhaDev** [AkaruiDevelopment/music#1]

**Comment by USERSATOSHI** [comment]
what is the error

**Comment by SulistinhaDev** [comment]
> qual é o erro 
posso mandar o meu projeto, pois estou tendo problemas de tirar print no pc

**Comment by USERSATOSHI** [comment]
if you use replit

you have to use nix environment instead of nodejs

and have to install both nodejs and python in it

other way

https://replit.com/@Leref/aoijs-starter-music?v=1
