### ISSUE TITLE
[BUG] $queue - incorrect position index of current track playing

### ISSUE THREAD

**Issue by AstrooKai** [AkaruiDevelopment/music#11]
### Current Behavior

The position of the current track playing is displayed incorrectly. There are instances where the position of the playing track is `0` and sometimes `1`. When the playing track is displayed as `1`, the position of the next track in the queue remains `1`, causing a double `1` in the queue list.

### Expected Behavior

The position of the current track playing should be displayed as `1` in the long queue list with the correct position numbers for the following tracks in the queue.

### Reproduce where the current track playing is displayed as `0`
```php
$queue[1;10;**{position}.** {title} - {artist}\nRequested by: {requester.user.username}\n]
```
### Reproduce where the current track playing is displayed as `1`, but the next track remains `1`
```php
$queue[1;10;{position}. {title} - {artist}\nRequested by: {requester.user.username}\n]
```
It's unclear and confusing how increasing the font weight of the `{position}` alters its behavior.

### Environment

```markdown
Environment: Visual Studio Code (v1.85.2)
NodeJS: v21.5.0
AoiJS: v6.7.1
```

### Anything else?

It would also be a convenience to remove the comma (`,`) at the beginning of the position since it requires additional functions _(e.g. `$replaceText`)_ to remove this, but doing so may also remove the commas that are in the titles or authors since wrapping the `{position}` inside the function doesn't work as intended _(the `{position}` doesn't get parsed first before being evaluated for text replacement)._

**Comment by Faf4a** [comment]
It's a little confusing but,

when the queue length is below 1 it takes 0 as current, if its above it takes 1 as current and 0 as previous
