### ISSUE TITLE
$skipto is bugged!

### ISSUE THREAD

**Issue by vishvaaskr** [AkaruiDevelopment/music#13]
code: 
$InteractionReply[;{newEmbed:{description:Skiped to **$songInfo[title;$slashoption[no]]** by **$songInfo[artist;$slashoption[no]] ($slashoption[no])**}{color:#0a9afa}}]
$skipto[$slashoption[no]]
$onlyIf[$slashoption[no]!=0;> Please enter a valid number {options:{ephemeral}} {extraOptions:{interaction}}]
$onlyIf[$slashoption[no]>=0;> Please enter a valid number {options:{ephemeral}} {extraOptions:{interaction}}]
$onlyIf[$slashoption[no]<=$math[$queuelength-1];> Please enter a valid number {options:{ephemeral}} {extraOptions:{interaction}}]
$onlyIf[$queueLength!=0;Queue is empty]
$onlyif[$voiceid[$authorid]==$voiceid[$clientid];> Please join <#$voiceid[$clientid]> to skip {options:{ephemeral}} {extraOptions:{interaction}}]
$onlyif[$voiceid[$clientid]!=;> Not playing any tracks {options:{ephemeral}} {extraOptions:{interaction}}]

![image](https://github.com/AkaruiDevelopment/aoi.music/assets/89300922/efda4543-d6b0-4cf9-84d9-ad946b4ee650)

**Comment by Faf4a** [comment]
This was fixed.
