### ISSUE TITLE
$autoplay is bugged!

### ISSUE THREAD

**Issue by vishvaaskr** [AkaruiDevelopment/music#14]
It just plays only one extra track after queue is finished!

$if[$slashoption[option]==true]
$InteractionReply[;{newEmbed:{description:Autoplay enabled!}{color:#0a9afa}}]
$autoPlay[relative]
$endif
$if[$slashoption[option]==false]
$InteractionReply[;{newEmbed:{description:Autoplay disabled!}{color:#0a9afa}}]
$autoPlay[none]
$endif
$onlyif[$playerstatus==playing;Nothing is being palyed {extraOptions:{interaction}}]
$onlyif[$queuelength!=0;Nothing is being played {extraOptions:{interaction}}]
$onlyif[$voiceid[$authorid]==$voiceid[$clientid];> Please join <#$voiceid[$clientid]> to resume the track {options:{ephemeral}} {extraOptions:{interaction}}]

![image](https://github.com/AkaruiDevelopment/aoi.music/assets/89300922/cb561e8b-465b-4f45-833e-fda6dde6f423)

**Comment by Faf4a** [comment]
duplicate #9
