### ISSUE TITLE
[BUG] $hasPlayer is bugged

### ISSUE THREAD

**Issue by vishvaaskr** [AkaruiDevelopment/music#15]
### Current Behavior

On disconnecting the bot manually from VC. $hasplayer returns true

### Expected Behavior

It should return false as bot is disconnected from vc

### Steps To Reproduce

1. Let the bot join vc
2. Disconnect it manually using discord vc options
3. try evaling $hasPlayer

**Comment by Faf4a** [comment]
This isn't a bug, you didn't destory the player

**Comment by vishvaaskr** [comment]
talked to fafa :wait:
