### ISSUE TITLE
[BUG] The player's status suddenly changes to idle

### ISSUE THREAD

**Issue by MrShidoKageno** [AkaruiDevelopment/music#23]
### Current Behavior

It’s not uncommon for a player to go into idle status before the end of a track and refuse to play the next track in the queue (if any).

### Expected Behavior

It’s not uncommon for a player to go into idle status before the end of a track and refuse to play the next track in the queue (if any). "If the player unexpectedly goes into idle state and does not start the next track, this may indicate a problem with the queue or playback, and it is worth considering this as a possible bug or error in the queue processing logic."

### Steps To Reproduce

try to add a few tracks to the queue or use a loop, at some point it will work.

### Environment

```markdown
Nodejs: 22.7.0
Aoi.js: github latest version (#6)
Aoi.music: latest (v1.2)
Config:
const voice = new AoiVoice(client, {
   devOptions: {
     debug: false,
  },
  requestOptions: {
    offsetTimeout: 1500,
    soundcloudLikeTrackLimit: -1,
    youtubePlaylistLimit: -1,
    spotifyPlaylistLimit: -1
  },
  searchOptions: {
   youtubeAuth: true,
   youtubeToken: true,
   spotifyAuth: {
       clientId: "0000000",
       clientSecret: "xxxxxx"
   },
   youtubegl: "US",
   youtubeClient: "ANDROID",
   youtubeToken: true
   }
});
voice.addPlugin(PluginName.Cacher, new Cacher("memory"));
voice.addPlugin(PluginName.Filter, new Filter({
    filterFromStart: false
})),
voice.bindExecutor(client.functionManager.interpreter);
voice.addEvent(PlayerEvents.TrackStart);
voice.addEvent(PlayerEvents.TrackEnd);
voice.addEvent(PlayerEvents.QueueEnd);
voice.addEvent(PlayerEvents.AudioError);
```

**Comment by Faf4a** [comment]
That happens most likely because of an audio error.

**Comment by MrShidoKageno** [comment]
> Скорее всего, это происходит из-за звуковой ошибки.

but what is the reason for the audio error?

**Comment by Faf4a** [comment]
Good question, unfortunately without the error your bot returns I cannot answer this.
