### ISSUE TITLE
[BUG] Queue Not Listing Properly While In Loop

### ISSUE THREAD

**Issue by ItzMann** [AkaruiDevelopment/music#4]
### Current Behavior

When the loop status is set to queue, then it doesn't rearrange the song list according to its position.

For example, if I enable the queue loop and the current song name is 'Something', then after the track ends it still keeps the song 'Something' at first position.

### Expected Behavior

It mus've rearranged the song list according to thier postion.

### Steps To Reproduce

1. Add some songs to queue...
2. Put queue on loop.
3. Check queue after one track ends.
4. You'll see that they aren't rearranged.

### Environment

```markdown
aoi.music version: dev version
node.js: 18.x
aoi.js: 6.x
```

**Comment by ItzMann** [comment]
No idea what to put inside 'Steps to Reproduce', so I put the steps to see the bug... : )

**Comment by USERSATOSHI** [comment]
hmm ok that does make sense 
issue is only with with bidirect and default type i assume as fonly type shifts the queue

**Comment by ItzMann** [comment]
no, the same issue is with fonly type too

**Comment by ItzMann** [comment]
looks good so far now
