### ISSUE TITLE
[BUG] $autoplay func

### ISSUE THREAD

**Issue by tyowk** [AkaruiDevelopment/music#9]
### Current Behavior

smth like this
![Screenshot_20231217-182700](https://github.com/AkaruiDevelopment/aoi.music/assets/126280064/a58cbeac-7e67-4534-801b-8c4935b166b2)

### Expected Behavior

I hope this bug is fixed soon.

### Steps To Reproduce

-

### Environment

```markdown
nodejs 18
Aoi.js latest
```

**Comment by Faf4a** [comment]
cc @USERSATOSHI

**Comment by Faf4a** [comment]
wont be fixed until v3
